### ISSUE TITLE
Language server crashes (ERROR: LoadError: Invalid response:)

### ISSUE THREAD

**Issue by kafisatz** [julia-vscode/SymbolServer.jl#27]
I am running into the issue below. Any ideas how I can fix this? (or further investigate this).
The server crashes all the time (when I use VS Code)

```
[ Info: Started symbol server
[ Info: Executing .juliarc.jl...
[ Info: Language Server crashed with
[ Info: ErrorException("Invalid response:\ntrue")
[ Info: done.
ERROR: LoadError: Invalid response:
true
Stacktrace:
 [1] error(::String, ::Bool) at .\error.jl:42
 [2] request(::SymbolServerProcess, ::Symbol, ::Nothing) at c:\Users\myusername\.vscode\extensions\julialang.language-julia-0.11.6\scripts\languageserver\packages\SymbolServer\src\SymbolServer.jl:40
 [3] get_installed_packages_in_env(::SymbolServerProcess) at c:\Users\myusername\.vscode\extensions\julialang.language-julia-0.11.6\scripts\languageserver\packages\SymbolServer\src\SymbolServer.jl:108
 [4] getstore(::SymbolServerProcess) at c:\Users\myusername\.vscode\extensions\julialang.language-julia-0.11.6\scripts\languageserver\packages\SymbolServer\src\SymbolServer.jl:67
 [5] run(::LanguageServerInstance) at c:\Users\myusername\.vscode\extensions\julialang.language-julia-0.11.6\scripts\languageserver\packages\LanguageServer\src\languageserverinstance.jl:34
 [6] top-level scope at c:\Users\myusername\.vscode\extensions\julialang.language-julia-0.11.6\scripts\languageserver\main.jl:26 [inlined]
 [7] top-level scope at .\none:0
 [8] include at .\boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at .\loading.jl:1044
 [10] include(::Module, ::String) at .\sysimg.jl:29
 [11] exec_options(::Base.JLOptions) at .\client.jl:266
 [12] _start() at .\client.jl:425
in expression starting at c:\Users\myusername\.vscode\extensions\julialang.language-julia-0.11.6\scripts\languageserver\main.jl:5
[Info  - 11:30:53] Connection to server got closed. Server will restart.
[ Info: Started symbol server
[ Info: Executing .juliarc.jl...
[ Info: Language Server crashed with
[ Info: ErrorException("Invalid response:\ntrue")
[ Info: done.
ERROR: LoadError: Invalid response:
true
```

**Comment by kafisatz** [comment]
Yes it is still the case.
I am using the vscode plugin 0.12.0 alpha7 (most recent).  The language server still crashes. How can I check which version of  SymbolServer is running?

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/SymbolServer.jl/commit/7f95a0e943b188bda6000c94d15ad91de4e03cb4 should fix this, can you git pull inside the SymbolServer directory? (this should be ~/.vscode/extensions/julialang.language-julia-0.11.6/scripts/languageserver/packages/)

**Comment by davidanthoff** [comment]
I just released a new alpha [here](https://github.com/julia-vscode/julia-vscode/releases/tag/v0.12.0-alpha.8), probably easiest to check with that one whether this is fixed or not.

For now I'm going to close this issue, given that @ZacLN thinks it is all sorted out.

**Comment by kafisatz** [comment]
I am on 12.0.alpha-7 now.
I downloaded the master fo SymbolServer (as zip from Github) and extracted into that folder. 
VSCode still says it is crashing....

**Comment by kafisatz** [comment]
This is still not working for me.
I am not quite sure where things fail, but I am not able to run ` ssp = SymbolServer.SymbolServerProcess(p, nothing, Dict())` .

I previously looked into this and I think it failed at the snippet below (where I received true as a response). 
```
payload=nothing
serialize(server.process, (:get_installed_packages_in_env, payload))
ret_val = deserialize(server.process)
```

I  tried finding the issue, but I am unable to execute the last line in the snippet below (why?)
```
c_users_myuser="C:\\Users\\my_username\\"
c_users_myuser="C:\\Users\\bernhard.konig\\"

conn = stdout
#(outRead, outWrite) = redirect_stdout()
ls_debug_mode = true #false
lsdir=joinpath(c_users_myuser,".vscode\\extensions\\julialang.language-julia-0.12.0-alpha.8\\scripts\\languageserver")
@assert isdir(lsdir)

#empty!(LOAD_PATH)
#push!(LOAD_PATH, joinpath(lsdir, "packages"))
#push!(LOAD_PATH, "@stdlib")
import Pkg 
Pkg.activate(joinpath(lsdir,"packages"))

using LanguageServer, Sockets, SymbolServer

while size(Base.ARGS,1)<5;push!(Base.ARGS,"")end;
Base.ARGS[1]=joinpath(c_users_myuser,".julia","environments","v1.0")
Base.ARGS[2]="--debug=no"
Base.ARGS[3]="\\\\.\\pipe\\vscode-language-julia-lscrashreports-27664"
push!(Base.ARGS,"")

#server = LanguageServerInstance(stdin, conn, true, Base.ARGS[1], Base.ARGS[4], Dict())
@which LanguageServerInstance(stdin, conn, true, Base.ARGS[1], Base.ARGS[4], Dict())
server = LanguageServerInstance(stdin, conn, true, Base.ARGS[1], Base.ARGS[4], Dict())
@which run(server)
#the above line fails for me

#server.symbol_server = SymbolServer.SymbolServerProcess(depot = server.depot_path, environment=server.env_path)
#the above line fails for me

@which SymbolServer.SymbolServerProcess(depot = server.depot_path, environment=server.env_path)
#SymbolServer.SymbolServerProcess(depot = server.depot_path, environment=server.env_path)
#the above line also fails

#function Base.run(server::LanguageServerInstance)
using StaticLint
    #server.symbol_server = StaticLint.SymbolServer.SymbolServerProcess(depot = server.depot_path)
    #@info "Started symbol server"
    #server.packages = StaticLint.SymbolServer.getstore(server.symbol_server)

    #function SymbolServerProcess(;environment=nothing, depot=nothing)
        jl_cmd = joinpath(Sys.BINDIR, Base.julia_exename())
        client_process_script = joinpath(joinpath(lsdir,"packages","SymbolServer","src"), "clientprocess", "clientprocess_main.jl")
        @assert isfile(client_process_script)
        
        env_to_use = copy(ENV)
        #if depot!==nothing
        #    if depot==""
        #        delete!(env_to_use, "JULIA_DEPOT_PATH")
        #    else
        #        env_to_use["JULIA_DEPOT_PATH"] = depot
        #    end
        #end
        environment=nothing

        p = if environment===nothing
            open(Cmd(`$jl_cmd $client_process_script`, env=env_to_use), read=true, write=true)
        else
            open(Cmd(`$jl_cmd --project=$environment $client_process_script`, dir=environment, env=env_to_use), read=true, write=true)
        end

        ssp = SymbolServer.SymbolServerProcess(p, nothing, Dict())
        #the above line fails for me 'no method matching SymbolServerProcess' 
        
#        get_context(ssp)
#        return ssp
```
